replicaCount: 1
applicationName: tailwindtraders

image:
  repository: ttacro5nrv3jcbbezi.azurecr.io/product.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: ConnectionString
    - name: ProductImagesUrl
    - name: ProductDetailImagesUrl
    - name: ProductVisitsUrl
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
