replicaCount: 1
applicationName: tailwindtraders

image:
  repository: ttacro5nrv3jcbbezi.azurecr.io/image-classifier.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
